### ISSUE TITLE
Redundant classes question

### ISSUE THREAD

**Issue by brunopbarrote** [ivanpaulovich/clean-architecture-manga#101]
Hi!
I've really love how this project is organized, and i've been working with this structure for a while now. But there is something that i personally don't like muc: repeat a controller for multiples usecases.
In your sample, in most of use cases we have AccountsController again. or IOutputPort. It's more organized, but i still think it's redundant.

Do you have any particular reason for this, or can help me clarifying this?

Thanks in advance!

**Comment by phmatray** [comment]
Hello @brunopbarrote ,

These controllers can be seen as partial classes and are used to create the api definition of swagger.

Moreover, if you have two identical definitions in two controllers that have the same name, then Swagger will not be able to build the API definition.

**Comment by ivanpaulovich** [comment]
Hi @brunopbarrote,

I'd like to add more info to the @phmatray  answer.

* **OCP** Classes should be closed for modification. It means that when adding a new feature it is better to add a new class implementation instead of modifying them. Later you can decommission the old class.

Although we can not always achieve this goal, specially when the code is closer to the user interface. The solution with separated folders adds extra work that works good for microservices, if you are working in a project that has a high number of operations you can merge the classes without much effort.

* **SRP** Classes to be responsible for a single Actor. It means that a class should concern about a single consumer, it is very easy to achieve that with a single method per class. Of course, it is not the perfect solution because every business implementation has different requirements that was the way I saw to be simple to teach on this project. 

if your actions are used at the same moment, by the same actors you should consider merging them. In the manga project the `Withdraw`, `Deposit` and `Transfer` could be merged.

I would definitely separate the `Close` from the other classes.

Let me stop here ;)
