### ISSUE TITLE
Password value object

### ISSUE THREAD

**Issue by phmatray** [ivanpaulovich/clean-architecture-manga#102]
Hello Ivan, 

How should we store a password in a value object? Ideally I think the field should contain a hashed password value?

However, how to hash a password without depending on the .NET framework in order not to break the domain's responsibilities? 

Also, what are the rules to be implemented as part of this implementation? For a secure password, here are some rules that could be applied.

* 12 characters minimum
* 30 characters maximum
* one number minimum
* one capital letter minimum
* A punctuation mark OR a special character (dollar, hash,...) minimum

**Comment by leandrofagundes** [comment]
Hi @phmatray,

Why can't we use the .Net Framework to hash the password? I guess we can't import third party libraries on application/domains layer, but we should be able to use anything the .Net by itself give to us. 
Maybe I just understood wrong your point, sorry for that, but if you are not getting a new package from someone else then Microsoft .Net Framework, I guess you are ok.

**Comment by ivanpaulovich** [comment]
Hi @phmatray,

The challenge in a `PasswordValueObject` is to hash it ideally using an external service. As you are used to the code base, our value objects are instantiated with `new` which makes hard to get a service from the container.

To overcome this limitation, you will need a PasswordFactory (or builder) that is initialized with the HashingService and it creates `PasswordValueObject` though a string password or any user input.

Later on, the same issue will happen with a `MoneyValueObject` that supports multiple currencies, we will need a `CurrencyService` and a `MoneyFactory`.

**Comment by leandrofagundes** [comment]
Hey @ivanpaulovich, I saw your factories and I know the pattern (I already read a lot about the 23 GoF patterns) but as I said before, I'm too much visual.

Know you tell @phmatray to bring a factory instead instantiate classes directly. 

Can you explain a little bit this limitation you've said, please?
Can you give an example why the solution will get limited without the factory?

Thanks

**Comment by ivanpaulovich** [comment]
Hey @leandrofagundes,

We are saying that the PasswordObject will need to hash the plain-text password via the `HashingService` . As the `PasswordObject` is a ValueObject it is not the best class to have a dependency on an service.

My suggestion is that we design a Builder or a Factory that receives the `HashingService` in the constructor.

so we can use like:

```c#
PasswordValueObject mypassword = passwordFactory.New("MyPlainTextPassword2019");
```

**Comment by leandrofagundes** [comment]
So, it's ok to Factory classes receive the service (with injection, I guess)? 

My question about factories is the weird way to figure those factories on huge projects. It's always one factory per component, or how many factories do you have?

**Comment by ivanpaulovich** [comment]
> So, it's ok to Factory classes receive the service (with injection, I guess)?

Sure. They will have constructor dependencies.

> or how many factories do you have?

**SRP** can help you decide in designing one or multiple factories. If these factory methods are used by the same actors, in the same moment, in the same way so the `Controller` is a single Actor. It means you can group these factories into one.

We grouped the entity factory methods into one because, most methods that use `NewAccount(..)` will most probably use `NewCredit(..)`. It means the same actor uses the methods, so they are grouped.

https://github.com/ivanpaulovich/clean-architecture-manga/blob/master/src/Infrastructure/EntityFrameworkDataAccess/EntityFactory.cs

**Comment by leandrofagundes** [comment]
Amazing! 

Just another question, I hope it could be the last one (for while).

`  public ICustomer NewCustomer(
            ExternalUserId externalUserId,
            SSN ssn,
            Name name) => new Customer(externalUserId, ssn, name);`

How do I Update this customer, changing it's name? 
Do you change your Name property to allow setters?
Create a method SetName to allow setters?
Do you create a new method on the factory class to NewCustomer with the Primary Key parameter?
Another other (and better) way?

**Comment by ivanpaulovich** [comment]
Hey @leandrofagundes,

The factory should be used when creating a new customer. Something like:

```c#
var newCustomer = _entityFactory.NewCustomer(externalId, ssn, name);
_customerRepository.Add(newCustomer);
_unitOfWork.Save();
```

Later on you find out a new UseCase for Update the Customer Personal Details, then you implement a use case like:

```c#
var existingCustomer = _customerRepository.Get(input.CustomerId);
existingCustomer.UpdatePersonalDetails(ssn, name);
_customerRepository.Save();
```

Please notice that I created the `UpdatePersonalDetails(SSN, Name)` instead of `SetSSN` and `SetName` because they are changed together. If you find lots of setters being used in sequence, have a second thought and merge them.

What do you say?

**Comment by leandrofagundes** [comment]
I thought about it but I want someone to tell me I was on the right way.
I came from a school where Getters and Setters were free with no rules, so the night came and the chaos resides on our code.
Now, my main goal is to learn as much as I can but I'm not the kind of guy who just repeats what everybody else does without knowing the reason.

Sorry for been asking soo much, I hope a day I can start helping your repo here. 
After reading twice the Clean Architecture Book, your GitHub is the most accurate and you are a really good person.
I'll be always praying for the best and success to you Ivan.
ps: I needed like a week to realize where are you from! ROFL

**Comment by ivanpaulovich** [comment]
Hey @leandrofagundes,

I felt the same way in many projects, I hope you can improve the code base a little bit at the time 😄 
It is good that you are asking because the discussion could help many people and I guess many developers are looking for the same answers.

Actually I would like to add your name to the project contributors (first page). Is that ok?
I appreciate the feedback 🙏

**Comment by leandrofagundes** [comment]
It'll be such an honor, but, how can I contribute to the project?
Let me know if there is something I can do.

**Comment by ivanpaulovich** [comment]
@all-contributors please add @leandrofagundes for question.

**Comment by ivanpaulovich** [comment]
> It'll be such an honor, but, how can I contribute to the project?

You are already contributing with questions, my fault we don't have well described issues that you could work on. I am gonna open some issues and you can pick them up if you want to.

**Comment by ivanpaulovich** [comment]
As we moved to OAuth2 this is not needed anymore. Thanks to all contributions.
