### ISSUE TITLE
Using ValueObjects for different entities should be avoid?

### ISSUE THREAD

**Issue by leandrofagundes** [ivanpaulovich/clean-architecture-manga#115]
If we add a Bank Entity where Bank should have a Name property, should it be the same Name of Customer?

But if the rules of Customer or Bank should have an additional implementation like: Bank Name should have only 10 characters, should we build UserName VO and BankName VO?

**Comment by ivanpaulovich** [comment]
Hey @leandrofagundes,

I suggest the TDD Outside-In approach. Design the API from the UseCases usage, deffer ValueObjects because they can change a lot in the earlier stages. So start with primitive types like `string`, `int` and `bool`.

I consider the Value Objects very specific to the Entity they are part of. These should be separated in `BankName` and `CustomerName` value objects.
