### ISSUE TITLE
Why should we have an Entity on Domain and a class inheriting the Entity on the Infrastructure Layer?

### ISSUE THREAD

**Issue by leandrofagundes** [ivanpaulovich/clean-architecture-manga#119]
Why should we have an Entity like Debit on Domain project (Domain Layer) and another one inside Infrastructure with the same name (Debit) which inherits from the Debit on Domain Project?

I know it's hard to see advantages on this project yet but what are the real advantages using this approach?

**Comment by bommen** [comment]
Throwing my hat in the ring: at least one reason I can see for inheriting the Domain entities in the Infrastructure project:
Infrastructure frameworks like EFCore may require certain class elements (empty constructor) that may not be present in the Domain entities;

Maybe there are some other reasons, but I can think of at least this one.

**Comment by leandrofagundes** [comment]
Thanks @bommen, I'll keep it open for one day or two if someone else want to contributes, but make sense!

**Comment by ivanpaulovich** [comment]
Hey all,

I am happy these question came up. @bommen is correct to say that certain class elements are required for EFCore and they are not needed (not desired) in the Domain. Let me try clarify it more.

* The entity interfaces (eg. IAccount, ICustomer, ICredit, IDebit) are the **Highest Level** in our design and they are consumed by the Use Cases, they are designed to fulfil the Use Cases needs only! If you need to change their signature it should be motivated by the Use Cases implementation. Please notice the getters/setters are unnecessary because use cases consume the very specific methods available.
* Domain Entities (eg. Account, Customer) implement the business rules and the Use Cases are their consumer. At this level we don't need to think about persistence, I decided to have `protected setters` and not implement the foreign properties (eg. Account class does not have CustomerId property).
* The Output/Output messages are low level, very specific to interact with the user and serializable.
* The Infrastructure Entities are the lowest level, they target the database and should be serializable, we need to add these elements (setters) and together with the `MangaContext` we create rules that make possible persist these objects in the database (eg. Account has a CustomerId property).

I explain a little bit in the [Clean Architecture Essentials video](https://www.youtube.com/watch?v=hZGF6RHrr8o).

These is what I remember at this time.

**Comment by leandrofagundes** [comment]
You got my like and my subscribe!
Nice job Ivan! Thank to you for and @bommen, your hat fits well ;)
