### ISSUE TITLE
Question about mediator for executing use cases

### ISSUE THREAD

**Issue by dotarj** [ivanpaulovich/clean-architecture-manga#135]
Hello Ivan,

Another question, I see that you've recently added the mediator pattern to execute use cases from controllers. By using the mediator, the controller does not directly call the execute method of the use case, so it does not "know" that the use case exists. On the other hand, what is the downside of the controller "knowing" the use case interface? I see the benefits of the mediator pattern, I just wonder what the benefits are in this case.

What is the benefit of using the mediator pattern for executing use cases?

Thanks!

**Comment by ivanpaulovich** [comment]
Just to clarify the User Interface should depend on a light-weight protocol 

> On the other hand, what is the downside of the controller "knowing" the use case interface? 

It is not a big downside, by design each controller depend on a specific UseCase interface (Port). If you are fine setting a specific UseCase on every Controller so there is no issue.

> What is the benefit of using the mediator pattern for executing use cases?

1. The Mediator unifies all use cases (Ports) on a single bus that knows the destinations and allows a common failure handling, retry and logging (those features are not ready yet).
2. Mediator is the initial step for a even-driven / event-sourcing solution that I am heading to, perhaps I should create a Project Road map somewhere.

The downside of Mediator is that it brings another layer of abstraction.

**Comment by dotarj** [comment]
Thanks for the reply!
