### ISSUE TITLE
c# Interfaces without properties

### ISSUE THREAD

**Issue by pendenaor** [ivanpaulovich/clean-architecture-manga#157]
Hi,

May be i'm missing something, but interfaces (in the C# sense of word) in this project don't have any property definitions. Could you explain the rational behind that ?

Thanks.

**Comment by rcarneironet** [comment]
An abstraction can be used for both properties or methods. I don’t fully understand your question.

**Comment by ivanpaulovich** [comment]
Hey @pendenaor,

I guess you refer to `IAccount`, `ICustomer` and other entities abstractions which does not expose most of getters and setters. It is because these properties are not used by Use Cases, so they don't need to exist. The rule of thumb here is:

> You design an abstraction aiming an specific user. The abstraction here are entities and the user are use cases.

The only components that need to know the entities properties are the ones on the edges of the application (User Interface or the Persistence layers).

@rcarneironet 🍺 😄

**Comment by pendenaor** [comment]
@rcarneironet i agree and i'm sorry if my question was not clear enough.

@ivanpaulovich thanks to made that clear. I was concerned by `src/Domain/Security/Services/IUserService.cs`

**Comment by ivanpaulovich** [comment]
> @ivanpaulovich thanks to made that clear. I was concerned by `src/Domain/Security/Services/IUserService.cs`

I see a semantic difference between a method and a get property. 

The intent of `IUserService` method implementations is to access a remote resource, it is more clear as methods. While I see c# properties as using the own object data to retrieve information.

On several other places we use C# properties 😎

**Comment by pendenaor** [comment]
@ivanpaulovich Thanks again.
