### ISSUE TITLE
Versioned UseCase clarification

### ISSUE THREAD

**Issue by leandrofagundes** [ivanpaulovich/clean-architecture-manga#174]
Hi @ivanpaulovich,

I was wondering how make sense to have a Controller for each Version but the usecase on manga is the same.
Should we create an UseCaseV2? Can you explain a little about the correct implementation of versions?

**Comment by ivanpaulovich** [comment]
Hi @leandrofagundes,

This is an old question, let me try to help.

There are too many versioning strategies that I can't bring up the "best practices" on this subject.
Most of the time the versioning is made in the User Interface layer because it is on startup that the components and DI are initialized.

I use to have an interface IUseCaseV2 to mark the dependency injection and BTW there are [other ways to do that](https://stackoverflow.com/questions/39174989/how-to-register-multiple-implementations-of-the-same-interface-in-asp-net-core).

**Comment by ivanpaulovich** [comment]
Closing as there is no new information.
