### ISSUE TITLE
TypeScript Exception

### ISSUE THREAD

**Issue by generalossig** [ivanpaulovich/clean-architecture-manga#181]
Hi and thanks for the nice examples.

I try to start the application as described with

1. Building the solution
2. _npm install_ in the client app folder,
3. _dotnet run --project src/WebApi/WebApi.csproj --environment="Development"_ in the root folder

But my browser gives me a 

> TypeError: Cannot read property 'credits' of undefined

When I navigate to _Manage Accounts_ => _Transaction_ . It seems I can't do anything beside this.

I would love to see this app running, but unfortunetaly I am not familiar at all with the techniques.
Can anybody please give me a hint how to solve the issue?

![image](https://user-images.githubusercontent.com/56273360/82588929-ba890700-9b9b-11ea-819d-9d70b5c3c79a.png)

**Comment by ivanpaulovich** [comment]
Hi @generalossig,

The bug you reported was fixed on the latest update. 

I need to let you know that the front end is still in the experimental phase. I wish a frontend engineer takes a lead on that because I did lots of mistakes on this part and it lacks features.

My advise for newcomers is to go through the tests and the Swagger UI.

**Comment by generalossig** [comment]
Thanks, 

I will try that. As soon as I learn what swagger ist :-)
