### ISSUE TITLE
Why do repositories interfaces located in domain project?

### ISSUE THREAD

**Issue by N31TH3R** [ivanpaulovich/clean-architecture-manga#187]
Hi Ivan!
I'm new to onion architecture and i don't understand that moment. Regard to IoC we need to place these interfaces to application layer instead of domain.

**Comment by ivanpaulovich** [comment]
Hey @N31TH3R,

Is this a question or statement?

If you wanna a clarification, let me try: not all interfaces need to be in the Application neither Domain layer. These packages define project organization, the scope the interfaces are available for usage or implementation.

Please add more details, so we could help.

/Ivan

**Comment by ivanpaulovich** [comment]
Hi again,

After I wrote my answer I realized that I should have provided an objective reason to place repositories interfaces in Domain Layer.

The reason is that I implemented [domain services ](https://github.com/ivanpaulovich/clean-architecture-manga/wiki/Domain-Driven-Design-Patterns#domain-service) in the domain later which depend on repositories.

I hope you found insights :)

**Comment by N31TH3R** [comment]
That was a question :)

So if you don't have any cross-domain logic and as a result any domain services then you don't have reasons to place interfaces to Domain layer, right?

Anyway, thank you for fast and clear answer.
