### ISSUE TITLE
[Question] How does the layering of this project match the clean architecture official diagram?

### ISSUE THREAD

**Issue by HamedFathi** [ivanpaulovich/clean-architecture-manga#239]
Hi,

I am a newbie in the clean architecture, Can anyone help me and explain 

**1.** How does the layering of this project match the clean architecture official diagram?

![CleanArchitecture](https://user-images.githubusercontent.com/8418700/94163875-38845400-fe95-11ea-954d-6e73dfe3373c.jpg)

Is it correct?

| Clean     | Manga                           |
|-----------|---------------------------------|
| Entities  | Domain                          |
| Use Cases | Application (UseCases/Services) |
|Controllers/Gateways/Presenter|Infrastructure|
|Devices/Web/DB/UI/External Interfaces|WebApi|

I am looking for a comparative comparison to better understand how layering works. Can anyone explain it with details? 
How to map the current project with the official image?
Unfortunately for me, clean architecture is not as transparent as onion architecture!

**2.** How did the Manga implement this part of the diagram? (example please)

![image](https://user-images.githubusercontent.com/8418700/94165160-c9a7fa80-fe96-11ea-8b91-ecd4c3f03345.png)

**Comment by cquirosj** [comment]
I cannot speak about the layering of the code of this repo but, since you are not familiar with clean architecture but you do with onion architecture, something that have helped me is that Clean Architecture is a combination of Onion Architecture + Hexagonal (aka ports and adapters architecture). This article explains it very well: https://herbertograca.com/2017/09/28/clean-architecture-standing-on-the-shoulders-of-giants/
