### ISSUE TITLE
Question regarding the usecases

### ISSUE THREAD

**Issue by bobtoebes** [ivanpaulovich/clean-architecture-manga#27]
Hi Ivan,

Great repo, really usefull stuff!

I have one question though, while researching the ports and adapters pattern / hex arch I stumble upon the following issue:

Should each driver interface (port/usecase in your case) only do one thing? Or is it allow to have, lets say, a customer interface which allows for more than one action a customer.

My concern is that a project will become very big if I were to add an interface for each usecase.

Kind regards,

Bob

**Comment by ivanpaulovich** [comment]
Hi @bobtoebes!

That's an interesting question! In simple terms each port should have one single responsibility, my intention on my sample projects is to show how to comply with SRP.

But I have to say that **SRP** is the hardest SOLID principle to adhere correctly. To clarify **you can have multiple methods and still one responsibility**. Suppose that you have a few use cases in a "Product Catalog Management".

Use case Family 1
1. Add product.
2. Update product.

Use case Family 2
3. Publish product.
4. Disable product.

The use cases 1 and 2 could be part of a single port and be implemented together if they are: 

- used by the same actor (product administrator).
- updating the same properties.
- used at the same step in the system.

I consider that the use cases 3 and 4 could belong to a separated port because:

- they are used by another actor (product publisher).
- used in a different moment and less frequently.

So my short answer is that each port should have one use case family.

Regards,
Ivan
