### ISSUE TITLE
Interfaces on entities

### ISSUE THREAD

**Issue by citroenfris** [ivanpaulovich/clean-architecture-manga#29]
Hello,

First of all great repository! Good basis to get started with a clean arch service. I am wondering why you recently added interfaces on the entities? I've been told it is an an anti pattern. What exactly is the advantage of adding them (or removing) them? 

Thanks!

**Comment by ivanpaulovich** [comment]
Hi @citroenfris, thank you for the feedback!

I was waiting for this question to come up. First I will answer what happens when you don't have entities with interfaces:

* The classes are designed to support 2 consumers: the use cases and repositories. I would say that this practice violates the Single Responsibility Principle (SRP) and the Interface Segregation Principle (ISP).
* The immediate concern is that use cases have access to a bunch of getters/setters that they should not use, it breaks the encapsulation principle.
* From the "Clean Architecture" book I learned that *"a component should be abstract as it is stable (SAP)"*. Interesting to see that when we have a domain with 100% of concrete entities they are explicitly violating the principle.
* It is too easy to use the *new* keyword everywhere, see code smells on the "Adaptive Code" book. 

Let me stop pointing the issues and explain the reason why developers are using concrete entities: 

> The simple answer is that Entity Framework do not works well with abstract classes or interfaces, so developers break the design principles because of ORM constraints.

Next why you should implement **use cases** which uses **entities interfaces**:

* "Getters/Setters" are simple data accessors and should be encapsulated. Use cases should see only the "Entity Id" and its behaviours.
* Factories should return abstractions.
* ORM will map the concrete entities loosely coupled.
* Use cases will only see the business usage contracts, and repositories will have access to getters/setters to do the serialisation/deserialisation.

My last tip is:

> If you are getting introduced to this architecture style it is fine to not have entities interfaces and factories. However, after a while I suggest to step up to a more advanced design which I am showing on this project.

Best,
Ivan
