### ISSUE TITLE
Add Localization feature

### ISSUE THREAD

**Issue by luizgustavogp** [ivanpaulovich/clean-architecture-manga#34]
Hi Ivan, first of all, great job. 

Based on this architectural proposal, how would you suggest adding localization capability to this project? I'm asking it because APS.NET core provides great support for localization, but when I thinking about Domain Layer, Application Layer it is not so clear to me. My questions are: 
**1 - Where the resource files should be?**
**2 - How we can resolve the domain model and value objects?**
**3 - How would you solve it thinking in tests, business rules?** 

Thank you.

**Comment by ivanpaulovich** [comment]
Hi @luizgustavogp!

Interesting question! I think I will implement it soon.

Do you mean localizing the messages in **Value Objects** and **Error Messages**? I won't go for it.

Instead, I suggest to Localize the Presentation layer. In this case, you could Localize the Presenters objects by injecting a service that have access to Resource files.

1. Resources should live in the Presentation layer (WebAPI).
2. To localize messages I would replace all strings with my own `LocalizedString` value object, which to be instantiated it would require ID and Text values. Then when the I need to display the presenter would convert the LocalizedString to the localized version. What do you think?
3. Messages should not affect tests, could you give me an example?

Regards,

**Comment by ivanpaulovich** [comment]
@all-contributors please add @luizgustavogp for design and tests

**Comment by ivanpaulovich** [comment]
Hi @luizgustavogp,

I have been thinking about your question for the last days. I personally don't like FluentValidation for Domain Objects like Value Objects, Entities or Aggregates because I have total control on how to design them.

I think FluentValidation is a great tool when you need to Validate an object that you don't have control like a Request Object to a WCF service, you can add this validation extension with small effort.

Going back to the original question, if you want to Localize code like the following:

```
IAccount account = await _accountRepository.Get(input.AccountId);
if (account == null)
{
    _outputHandler.Error($"The account {input.AccountId} does not exist or is already closed.");
    return;
}

IDebit debit = account.Withdraw(input.Amount);

if (debit == null)
{
    _outputHandler.Error($"The account {input.AccountId} does not have enough funds to withdraw {input.Amount}.");
    return;
}
```

Then create Resource file on each assembly, like one for Application, one for Domain, WebApi and Infrastructure. I think it is a not intrusive solution.

Best,
Ivan

**Comment by luizgustavogp** [comment]
Hi @ivanpaulovich , thanks for thinking about that. I see. It makes sense.
I thought of creating one resource file per layer so as not to create too many dependencies.
Thank you Ivan for collaborating with the community.

**Comment by ivanpaulovich** [comment]
You are welcome!
