### ISSUE TITLE
Use Cases and MediatR

### ISSUE THREAD

**Issue by lilasquared** [ivanpaulovich/clean-architecture-manga#82]
First off really cool repo!  I was poking around in it and noticed your UseCases are quite similar to the pattern we use which revolves around MediatR.  Have you considered using MediatR instead of your custom use case abstractions?  Just curious if this library would play into the Clean Architecture you are trying to achieve or if it would cause any issues.  Thanks!

**Comment by ivanpaulovich** [comment]
Hi @lilasquared!

I appreciate the feedback :)

The `Use Cases abstractions` and the `RequestHandlers` from MediatR are quite similar by following the Single Responsibility Principle.

Unfortunately to use MediatR we need to bring the dependencies to the application layer, which in my point of view goes against the Hexagonal Architecture Style (_an application independent of frameworks and 3rd party libraries_) and if we are not following Hexagonal then we are not in the Clean Architecture style.

I would love to see a feature in MediatR that I could setup my own `Request/RequestHandlers` interfaces.

Regards,
Ivan

**Comment by lilasquared** [comment]
In my projects I have an abstractions layer that wraps the MediatR interfaces with my own, and then my application depends on those.  Is that sufficient for the Hexagonal Architecture Style or is there something else that is required? I am also trying to make sense of why you have IUseCase redefined in each of the different UseCases.  Is there no place in Hexagonal Architecture Style for cross cutting concerns?  Wouldn't some shared logic make sense and be beneficial for enforcing certain patterns or reducing boilerplate core?

**Comment by ivanpaulovich** [comment]
> I have an abstractions layer that wraps the MediatR interfaces with my own, and then my application depends on those.

Interesting! I would like to check it out! 

To adhere to Hexagonal Architecture Style you need:

1. An abstraction that belongs to your own `Application Layer` and the implementation coupled in the `Infrastructure layer`.
2. A fake implementation for each dependency (ideally created first).

I created separated interfaces because I wanted to allow the developers to create different signatures if they wish, not necessarly a single Input argument.

Frameworks are allowed in the UI and in the Infrastructure. Shared code should be used behind an interface (library style).

**Comment by lilasquared** [comment]
Thanks again for the replies and insight.

In the realm of microservices I would imagine an enterprise or solution consisting of many different applications.  If each of these is to adhere to the hexagonal architecture pattern, and each also to make use of the same frameworks or libraries, would then a cross cutting "library" of abstractions be acceptable to reference in the Application layer?  I would imagine that replicating interfaces in every service / app would be a real pain.  When I am able to find that library of MediatR abstractions I'll be sure to share it with you!

**Comment by ivanpaulovich** [comment]
The Ports and Adapters are good for the realm of microservices especially because it focus on applications independence and autonomy.

I guess you are talking about an `Application.Abstractions` layer which contains interfaces like `IUseCase`, `IInput`, `IOutput` to guide the patterns and project organisation. If so I prefer that every project has his own set of interfaces because it will enforce **independence** and **autonomy**. As everything good in life it has the drawback that you need to ship it to every team and project!

On **Building Microservices** it is described an "Application Template" to accelerate the adoption of shared capabilities and concerns, with a template you can bootstrap these and that's the idea behind Manga and https://github.com/ivanpaulovich/dotnet-new-caju projects.

**Comment by ivanpaulovich** [comment]
Hi @lilasquared! 
Feel free to open new issues with additional information.
/Ivan

**Comment by lilasquared** [comment]
thanks @ivanpaulovich.  One final question I have (for now) is, what is the design factors that result in splitting the Domain layer from the Application layer?  You've mentioned that neither should have external dependencies, and it looks like the Application layer only depends on the Domain layer.  What is the purpose of the separation?

**Comment by ivanpaulovich** [comment]
Hi @lilasquared!
For small applications the Application and Domain layers could perfectly be a single `Core Layer`. Usually I separate these layers considering that my next step is adding sub domains.

1 Start with

```
Tests -> Core
```
 
2 Split Core to organize

```
Tests -> Application -> Core
```

3 Adding sub domains

```
Tests -> Application -> Products Catalog Sub Domain
                     -> Orders Sub Domain
```

**Comment by lilasquared** [comment]
Got it, thanks!

**Comment by ivanpaulovich** [comment]
Hey @lilasquared,

> First off really cool repo! I was poking around in it and noticed your UseCases are quite similar to the pattern we use which revolves around MediatR.

This thread motivated me to create the https://github.com/ivanpaulovich/FluentMediator in order to publish events and commands without coupling to framework interfaces.

Soon there will be a Clean Architecture sample using it.

**Comment by lilasquared** [comment]
Cool I checked it out a bit, will post comments in that repo for discussion

**Comment by ivanpaulovich** [comment]
Hey @lilasquared!

I updated the project to use FluentMediator, which do not require dependencies in the Domain layer. So closing this issue now 🍺
